server:
  port: 8888

spring:
  profile:
    active: native
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations
        git:
          uri: https://github.com/SantinoVega/Proyecto_Uno.git