server:
  port: 8761

spring:
  application:
    name: msvc-eureka
  #config:
  #  import: optional:configserver:http://localhost:8888

eureka:
  instance:
    hostname: localhost
  client:
    #register-with-eureka: false
    #fetch-registry: false
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/